#!/bin/sh

#
# VARIABLES
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#
# ARGUMENTS
#
DSN=$1
REST_PORT=$2
META_PORT=$3
DEBUG=$4

CMD="coffee $DIR/app/app.coffee \
    --dsn $DSN \
    --rest-port $REST_PORT \
    --meta-port $META_PORT"

#
# REQUIREMENTS
#
if [ $# -lt 3 ]; then
    echo "Usage:"
    echo "  ./run 'postgres://[DB_USER]:[DB_PASS]@[DB_HOST]/[DB_NAME]' [REST_PORT] [META_PORT]"
    exit 1
fi

#
# FUNCTIONS
#
function startServer {
    if [ "$DEBUG" == "debug" ]; then
        $CMD &
    else
        $CMD >/dev/null &
    fi
    PID=$!
}
function stopServer {
    kill $PID
}


#
# CONSOLE
#
echo ""
echo "#########################"
echo "Starting inspired-server"

#
# WARMUP inspired-server
#
startServer
sleep 10
stopServer
sleep 1

#
# START inspired-server
#
startServer

#
# CONSOLE
#
echo "PID: $PID"
echo "#########################"
echo ""

#
# RUN TESTS
#
casperjs test $DIR/src/tests/ \
    --pre=$DIR/src/pre.coffee \
    --includes=$DIR/src/inc.coffee \
    --post=$DIR/src/post.coffee \
    --port="$2"

#
# STOP inspired-server
#
stopServer

#
# CONSOLE
#
echo ""
echo "#########################"
echo "Stopped inspired-server"
echo "#########################"
echo ""