// Generated by CoffeeScript 1.7.1
(function() {
  var App;

  global.App = App = {
    Helpers: require('./helpers'),
    Entity: require('./entity'),
    Field: require('./field'),
    Server: require('./server'),
    Router: require('./router'),
    DB: require('./db'),
    isRemote: (process.browser != null) || process.mainModule.loaded
  };

  if (App.isRemote) {
    App.DB.adapter(new (require('./db/rest')));
  } else {
    App.DB.adapter(new (require('./db/pg')));
  }

  module.exports.App = App;

}).call(this);
