// Generated by CoffeeScript 1.7.1
(function() {
  var Boolean, Date, Float, Integer, MacAddress, Money, Password, String, Text, Time, Timestamp, Uuid, _Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _Base = (function() {
    function _Base() {}

    _Base.prototype["default"] = function() {
      return null;
    };

    _Base.prototype.length = function() {
      return null;
    };

    _Base.prototype.type = function() {
      return null;
    };

    _Base.prototype.isValid = function(value) {
      if ((this.length() != null) && (value != null) && value.length > this.length()) {
        return false;
      }
      return true;
    };

    return _Base;

  })();

  Boolean = (function(_super) {
    __extends(Boolean, _super);

    function Boolean() {
      return Boolean.__super__.constructor.apply(this, arguments);
    }

    Boolean.prototype.type = function() {
      return 'boolean';
    };

    return Boolean;

  })(_Base);

  Integer = (function(_super) {
    __extends(Integer, _super);

    function Integer() {
      return Integer.__super__.constructor.apply(this, arguments);
    }

    Integer.prototype.length = function() {
      return 10;
    };

    Integer.prototype.type = function() {
      return 'integer';
    };

    return Integer;

  })(_Base);

  Date = (function(_super) {
    __extends(Date, _super);

    function Date() {
      return Date.__super__.constructor.apply(this, arguments);
    }

    Date.prototype.type = function() {
      return 'date';
    };

    return Date;

  })(_Base);

  MacAddress = (function(_super) {
    __extends(MacAddress, _super);

    function MacAddress() {
      return MacAddress.__super__.constructor.apply(this, arguments);
    }

    MacAddress.prototype.type = function() {
      return 'macaddr';
    };

    return MacAddress;

  })(_Base);

  Money = (function(_super) {
    __extends(Money, _super);

    function Money() {
      return Money.__super__.constructor.apply(this, arguments);
    }

    Money.prototype.type = function() {
      return 'money';
    };

    Money.prototype["default"] = function() {
      return '123';
    };

    return Money;

  })(_Base);

  Float = (function(_super) {
    __extends(Float, _super);

    function Float() {
      return Float.__super__.constructor.apply(this, arguments);
    }

    Float.prototype.type = function() {
      return 'float8';
    };

    return Float;

  })(_Base);

  String = (function(_super) {
    __extends(String, _super);

    function String() {
      return String.__super__.constructor.apply(this, arguments);
    }

    String.prototype.length = function() {
      return 50;
    };

    String.prototype.type = function() {
      return 'varchar';
    };

    return String;

  })(_Base);

  Text = (function(_super) {
    __extends(Text, _super);

    function Text() {
      return Text.__super__.constructor.apply(this, arguments);
    }

    Text.prototype.type = function() {
      return 'text';
    };

    return Text;

  })(_Base);

  Time = (function(_super) {
    __extends(Time, _super);

    function Time() {
      return Time.__super__.constructor.apply(this, arguments);
    }

    Time.prototype.type = function() {
      return 'time';
    };

    return Time;

  })(_Base);

  Timestamp = (function(_super) {
    __extends(Timestamp, _super);

    function Timestamp() {
      return Timestamp.__super__.constructor.apply(this, arguments);
    }

    Timestamp.prototype.type = function() {
      return 'timestamp';
    };

    return Timestamp;

  })(_Base);

  Uuid = (function(_super) {
    __extends(Uuid, _super);

    function Uuid() {
      return Uuid.__super__.constructor.apply(this, arguments);
    }

    Uuid.prototype.type = function() {
      return 'uuid';
    };

    return Uuid;

  })(_Base);

  Password = (function(_super) {
    __extends(Password, _super);

    function Password() {
      return Password.__super__.constructor.apply(this, arguments);
    }

    return Password;

  })(String);

  module.exports = {
    _Base: _Base,
    Boolean: Boolean,
    Integer: Integer,
    Date: Date,
    MacAddress: MacAddress,
    Money: Money,
    Float: Float,
    String: String,
    Text: Text,
    Time: Time,
    Timestamp: Timestamp,
    Uuid: Uuid,
    Password: Password
  };

}).call(this);
