// Generated by CoffeeScript 1.7.1
(function() {
  String.prototype.uppercaseFirst = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

  module.exports = {};

}).call(this);
