// Generated by CoffeeScript 1.7.1
(function() {
  var Q, http;

  http = require('http');

  Q = require('q');

  if ((http != null) && (http.IncomingMessage != null)) {
    http.IncomingMessage.prototype.readData = function() {
      var data, deferred;
      deferred = Q.defer();
      data = new String;
      this.on('data', function(chunk) {
        return data += chunk;
      });
      this.on('end', function() {
        return deferred.resolve(data);
      });
      this.on('error', function(e) {
        return deferred.reject(e);
      });
      return deferred.promise;
    };
    http.IncomingMessage.prototype.readJSON = function() {
      return this.readData().then(function(data) {
        return JSON.parse(data);
      })["catch"](function(e) {
        throw String(e);
      });
    };
  }

  module.exports = http;

}).call(this);
