// Generated by CoffeeScript 1.7.1
(function() {
  var Router, url;

  url = require('url');


  /*
  	The REGEXP will match the following URLs:
  		/{name}
  		/{name}.{format}
  		/{name}/{id}
  		/{name}/{id}.{format}
  
  	The URL gets parsed into parts:
  		 *1: name
  		 *2: id OR `undefined`
  		 *3: format OR `undefined`
   */

  Router = (function() {
    Router.prototype.format = 'html';

    function Router(request) {
      this.request = request;
      this.url = url.parse(this.request.url, true);
      this.info = /^\/([a-z0-9_]+)(?:(?:\/([^.]+))?(?:\.([a-z]+))?)?$/.exec(this.url.pathname);
      console.log("[ROUTER - " + request.method + "]", this.info);
      if (!this.isValid()) {
        return;
      }
      this.name = this.info[1];
      this.id = this.info[2];
      this.format = this.info[3];
    }

    Router.prototype.isValid = function() {
      return this.info != null;
    };

    return Router;

  })();

  module.exports = Router;

}).call(this);
