// Generated by CoffeeScript 1.7.1
(function() {
  var Server, ServerHandler, http;

  http = require('./http');

  ServerHandler = {
    Meta: require('./server/meta'),
    Rest: require('./server/rest')
  };

  Server = (function() {
    function Server() {
      if (App.isRemote) {
        return;
      }
      http.createServer((new ServerHandler.Rest).handler).listen(8765);
      http.createServer((new ServerHandler.Meta).handler).listen(9876);
    }

    return Server;

  })();

  module.exports = Server;

}).call(this);
